<%
sphinx_server = SearchableModel.sphinx_servers.sample
raise 'missing sphinx server' unless sphinx_server
%>

staging:
  address: "<%= sphinx_server[:host] %>"
  port: "<%= sphinx_server[:port] %>"
  bin_path: "../sphinx/src"
  enable_star: 1
  min_prefix_len: 3
  dict: "keywords"

production:
  address: "<%= sphinx_server[:host] %>"
  port: "<%= sphinx_server[:port] %>"
  bin_path: "../sphinx/src"
  enable_star: 1
  min_prefix_len: 3
  dict: "keywords"
